AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI app on Lambda with Mangum

Resources:
  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      Runtime: python3.11
      CodeUri: ./
      Timeout: 30
      MemorySize: 512
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          DYNAMODB_ENDPOINT_URL:
            Ref: AWS::NoValue
          USER_TABLE_NAME:
            Ref: AWS::NoValue
