AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI app on Lambda with Mangum

Parameters:
  UserTableName:
    Type: String
    Default: petrock-nova-user-table

  PetTableName:
    Type: String
    Default: petrock-nova-pet-table

  DiaryTableName:
    Type: String
    Default: petrock-nova-diary-table

  ImageBucketName:
    Type: String
    Default: petrock-nova-image-bucket

  PetrockNovaApiSecretName:
    Type: String
    Default: petrock-nova-api-secrets

Globals:
  Function:
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: petrock-nova-api
        POWERTOOLS_LOG_LEVEL: INFO

Resources:
  PetrockNovaAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: PetrockNovaAPI
      StageName: prod
      Cors:
        AllowOrigin: "'*'"
        AllowCredentials: false
        AllowMethods: "'GET,POST,PUT,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"

  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      Runtime: python3.11
      CodeUri: ./
      Timeout: 30
      MemorySize: 512
      Events:
        PetrockNovaAPI:
          Type: Api
          Properties:
            RestApiId:
              Ref: PetrockNovaAPI
            Path: /{proxy+}
            Method: ANY
      Policies:
        - SecretsManagerReadPolicy:
          SecretName:
            Ref: PetrockNovaApiSecretName
        - DynamoDBCrudPolicy:
            TableName:
              Ref: PetTableName
        - DynamoDBCrudPolicy:
            TableName:
              Ref: UserTableName
        - DynamoDBCrudPolicy:
            TableName:
              Ref: DiaryTableName
        - S3CrudPolicy:
            BucketName:
              Ref: ImageBucketName
      Environment:
        Variables:
          DYNAMODB_ENDPOINT_URL:
            Ref: AWS::NoValue
          USER_TABLE_NAME:
            Ref: UserTableName
          PET_TABLE_NAME:
            Ref: PetTableName
          DIARY_TABLE_NAME:
            Ref: DiaryTableName
          S3_ENDPOINT_URL:
            Ref: AWS::NoValue
          IMAGE_BUCKET_NAME:
            Ref: ImageBucketName
          PETROCK_NOVA_API_SECRET_NAME:
            Ref: PetrockNovaApiSecretName

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value:
      Fn::Sub: "https://${PetrockNovaAPI}.execute-api.${AWS::Region}.amazonaws.com/prod"
