AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: DynamoDB Table for Petrock Nova

Parameters:
  UserTableName:
    Type: String
  PetTableName:
    Type: String
  DailyRecordTableName:
    Type: String
  ChatTableName:
    Type: String

Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 
        Ref: UserTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH

  PetTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 
        Ref: PetTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pet_id
          AttributeType: S
      KeySchema:
        - AttributeName: pet_id
          KeyType: HASH

  DailyRecordTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 
        Ref: DailyRecordTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pet_id
          AttributeType: S
        - AttributeName: date
          AttributeType: S
      KeySchema:
        - AttributeName: pet_id
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE

  ChatTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 
        Ref: ChatTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pet_id
          AttributeType: S
      KeySchema:
        - AttributeName: pet_id
          KeyType: HASH

Outputs:
  UserTableName:
    Description: User Table Name
    Value: 
      Ref: UserTable
  PetTableName:
    Description: Pet Table Name
    Value: 
      Ref: PetTable
  DailyRecordTableName:
    Description: DailyRecord Table Name
    Value: 
      Ref: DailyRecordTable
  ChatTableName:
    Description: Chat Table Name
    Value: 
      Ref: ChatTable