AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: DynamoDB Table for Petrock Nova

Parameters:
  UserTableName:
    Type: String
  PetTableName:
    Type: String
  DiaryRecordTableName:
    Type: String

Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 
        Ref: UserTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH

  PetTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 
        Ref: PetTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pet_id
          AttributeType: S
      KeySchema:
        - AttributeName: pet_id
          KeyType: HASH

  DiaryRecordTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 
        Ref: DiaryRecordTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pet_id
          AttributeType: S
        - AttributeName: date
          AttributeType: S
      KeySchema:
        - AttributeName: pet_id
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE

Outputs:
  UserTableName:
    Description: User Table Name
    Value: 
      Ref: UserTable
  PetTableName:
    Description: Pet Table Name
    Value: 
      Ref: PetTable
  DiaryRecordTableName:
    Description: DiaryRecord Table Name
    Value: 
      Ref: DiaryRecordTable