AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Lambda functions for Petrock Nova

Parameters:
  Environment:
    Type: String

  PetTableName:
    Type: String

  DiaryTableName:
    Type: String

Conditions:
  IsLocalEnvironment: 
    Fn::Equals: 
      - Ref: Environment
      - "local"

Globals:
  Function:
    Runtime: python3.11
    Architectures:
      - x86_64

Resources:
  GetPetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: petrock-nova-GetPetFunction
      CodeUri: ../resources/functions/pet_handler/
      Handler: pet_handler.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName:
              Ref: PetTableName
      Environment:
        Variables:
          DYNAMODB_ENDPOINT_URL: 
            Fn::If:
              - IsLocalEnvironment
              - "http://localstack:4566"
              - Ref: "AWS::NoValue"
          PET_TABLE_NAME:
            Ref: PetTableName

  GetDiaryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: petrock-nova-GetDiaryFunction
      CodeUri: ../resources/functions/diary_handler/
      Handler: diary_handler.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName:
              Ref: DiaryTableName
      Environment:
        Variables:
          DYNAMODB_ENDPOINT_URL:
            Fn::If:
              - IsLocalEnvironment
              - "http://localstack:4566"
              - Ref: "AWS::NoValue"
          DIARY_TABLE_NAME:
            Ref: DiaryTableName

  GetChatFunction:
      Type: AWS::Serverless::Function
      Properties:
        FunctionName: petrock-nova-GetChatFunction
        CodeUri: ../resources/functions/chat_handler/
        Handler: chat_handler.lambda_handler
        Policies:
          - DynamoDBReadPolicy:
              TableName:
                Ref: PetTableName
        Environment:
          Variables:
            DYNAMODB_ENDPOINT_URL:
              Fn::If:
                - IsLocalEnvironment
                - "http://localstack:4566"
                - Ref: "AWS::NoValue"
            PET_TABLE_NAME:
              Ref: PetTableName
