version = 0.1

[dev.deploy.parameters]
stack_name = "petrock-nova-infra"
resolve_s3 = true
s3_prefix = "petrock-nova-infra"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Environment=\"dev\""
image_repositories = []

[prod.deploy.parameters]
stack_name = "petrock-nova-infra"
resolve_s3 = true
s3_prefix = "petrock-nova-infra"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Environment=\"prod\""
image_repositories = []
