AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Parent SAM template

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - prod
    Default: prod
    Description: デプロイ先の環境

  UserTableName:
    Type: String
    Default: petrock-nova-user-table
    Description: ユーザーの情報を保存しておくDynamoDBのテーブルの名前
  PetTableName:
    Type: String
    Default: petrock-nova-pet-table
    Description: ペットの情報を保存しておくDynamoDBのテーブルの名前
  DiaryTableName:
    Type: String
    Default: petrock-nova-diary-table
    Description: ペットの日記を保存しておくDynamoDBのテーブルの名前

  PetImageBucketName:
    Type: String
    Default: petrock-nova-image-bucket
    Description: ペットの画像を保存しておくS3バケットの名前

Resources:
  DynamodbStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: templates/dynamodb.yaml
      Parameters:
        UserTableName:
          Fn::Sub: "${Environment}-${UserTableName}"
        PetTableName:
          Fn::Sub: "${Environment}-${PetTableName}"
        DiaryTableName:
          Fn::Sub: "${Environment}-${DiaryTableName}"

  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: templates/s3.yaml
      Parameters:
        PetImageBucketName:
          Fn::Sub: "${Environment}-${PetImageBucketName}"

  lamdaStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: templates/lamda.yaml
      Parameters:
        PetTableName:
          Fn::Sub: "${Environment}-${PetTableName}"

Outputs:
  UserTableName:
    Value:
      Fn::GetAtt:
        - DynamodbStack
        - Outputs.UserTableName
  PetTableName:
    Value:
      Fn::GetAtt:
        - DynamodbStack
        - Outputs.PetTableName
  DiaryTableName:
    Value:
      Fn::GetAtt:
        - DynamodbStack
        - Outputs.DiaryTableName

  PetImageBucketName:
    Value:
      Fn::GetAtt:
        - S3Stack
        - Outputs.BucketName
