name: Deploy Swagger UI docs

on:
  push:
    branches:
      - develop
    paths:
      - 'open-api/**'
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch to deploy'
        required: true
        default: 'develop'

permissions:
  contents: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli

      - name: Bundle OpenAPI spec
        run: redocly bundle open-api/open-api.yaml --output open-api/bundled.yaml

      - name: Generate Swagger UI static files
        uses: Legion2/swagger-ui-action@v1
        with:
          spec-file: open-api/bundled.yaml
          output: swagger-ui
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_SWAGGER_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Deploy to S3
        run: |
          aws s3 sync swagger-ui/ s3://${{ secrets.S3_SWAGGER_BUCKET_NAME }}/ --delete
