openapi: 3.0.0
info:
  title: Petrock Nova API
  description: Petrock Nova のバックエンド
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Local development server

tags:
  - name: user
    description: ユーザに関する情報を管理するAPI
  - name: pet
    description: ペットに関する情報を管理するAPI
  - name: diary
    description:  日記を管理するAPI
  - name: chat
    description: チャットを管理するAPI
  - name: s3
    description: S3に関するAPI

paths:
  /users/{user_id}:
    $ref: './paths/user.yaml#/users~1user_id'
  /pets/{pet_id}:
    $ref: './paths/pet.yaml#/pets~1pet_id'
  /pets/{pet_id}/diaries/{date}:
    $ref: './paths/diary.yaml#/pet~1pet_id~1diaries~1date'
  /pets/{pet_id}/chats:
    $ref: './paths/chat.yaml#/pet~1pet_id~1chats'
  /s3/presigned-url:
    $ref: './paths/s3.yaml#/s3~1presigned-url'
